# This workflow will build a docker container, publish it to Google Container Registry, and deploy it to GKE.
#
# To configure this workflow:
#
# 1. Ensure that your repository contains the necessary configuration for your Google Kubernetes Engine cluster, including deployment.yml, kustomization.yml, service.yml, etc.
#
# 2. Set up secrets in your workspace: GKE_PROJECT with the name of the project, GKE_EMAIL with the service account email, GKE_KEY with the service account key.
#
# 3. Change the values for the GKE_ZONE, GKE_CLUSTER and IMAGE environment variables (below).

name: Build and Deploy to GKE

on:
  push:
    branches:
    - master

# Environment variables available to all jobs and steps in this workflow
env:
  GKE_PROJECT: ${{ secrets.GKE_PROJECT }}
  GKE_EMAIL: ${{ secrets.GKE_EMAIL }}
  GITHUB_SHA: ${{ github.sha }}
  GKE_ZONE: us-central1-a
  GKE_CLUSTER: standard-cluster-1

jobs:
  phaseOne:
    name: Setup, Build, Publish, and Deploy
    runs-on: ubuntu-latest
    steps:

    - name: Checkout
      uses: actions/checkout@master

    # Setup gcloud CLI
    - uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
      with:
        version: '270.0.0'
        service_account_email: ${{ secrets.GKE_EMAIL }}
        service_account_key: ${{ secrets.GKE_KEY }}

    # Configure docker to use the gcloud command-line tool as a credential helper
    - run: |
        # Set up docker to authenticate
        # via gcloud command-line tool.
        gcloud auth configure-docker
      
    # Build the Docker image
    - name: Build
      run: docker build -t devops-lab/builder -f ./cicd/builder.Dockerfile .
           
  phaseTwo:
    name: Phase Two
    needs: [phaseOne]
    runs-on: ubuntu-latest
    strategy:
      matrix:
        app: [web, todos]
        include:
          - app: web
            fullName: app-web
          - app: todos
            fullName: service-todos
    steps:
    - name: Checkout
      uses: actions/checkout@master
    - name: Build
      run: docker build -t devops-lab/${{ matrix.app }} -f ./src/${{ matrix.fullName }}/Dockerfile .
    - name: Tag
      run: docker tag devops-lab/${{ matrix.app }} gcr.io/$GKE_PROJECT/${{ matrix.app }}:$GITHUB_SHA
    # Push the Docker image to Google Container Registry
    - name: Publish
      run: docker push gcr.io/$GKE_PROJECT/${{ matrix.app }}:$GITHUB_SHA
    # Deploy the Docker image to the GKE cluster
    - name: Deploy
      run: kubectl set image deployments/${{ matrix.fullName }} ${{ matrix.fullName }}=gcr.io/$GKE_PROJECT/${{ matrix.app }}:$GITHUB_SHA
